TEMPORAL_FEATURES_DIMENSION=  10
SPATIAL_FEATURES_DIMENSION=  4
TEMPORAL_EMBEDDING_DIMENSION = 64
SPATIAL_EMBEDDING_DIMENSION = 32
EMBEDDING_DIMENSION = SPATIAL_EMBEDDING_DIMENSION + TEMPORAL_EMBEDDING_DIMENSION
OUTPUT_DIMENSION = 3